# Configurações do Datasource para o PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/hoteleclipse
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Força o Hibernate a usar o dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Permite que o Hibernate crie e atualize as tabelas automaticamente no início
spring.jpa.hibernate.ddl-auto=update

# Desativa o H2 para este perfil
spring.h2.console.enabled=false
